import { Wall } from "./types";

export const autogeneratedMap: Wall[] = [
    { x: 100, y: 100, width: 200, height: 20 },
    { x: 300, y: 200, width: 20, height: 200 },
    { x: 500, y: 300, width: 160, height: 20 },
    { x: 700, y: 400, width: 200, height: 20 },
    { x: 900, y: 260, width: 20, height: 140 },
    { x: 200, y: 500, width: 260, height: 20 },
    { x: 600, y: 100, width: 20, height: 260 },
    { x: 800, y: 600, width: 180, height: 20 },
    { x: 1000, y: 100, width: 20, height: 200 },
    { x: 400, y: 600, width: 20, height: 100 },
    { x: 240, y: 240, width: 20, height: 100 },
    { x: 560, y: 440, width: 200, height: 20 },
    { x: 100, y: 360, width: 160, height: 20 },
    { x: 740, y: 200, width: 200, height: 20 }
];